# Generated by Django 2.1.8 on 2019-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20190812_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
