# Generated by Django 2.1.8 on 2019-08-12 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20190812_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Estd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date ESTD'),
        ),
    ]
