# Generated by Django 2.1.8 on 2019-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_auto_20190812_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Mobile_No',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Ph_No',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_request',
            name='Hostel_Mobile_No',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_request',
            name='Hostel_Ph_No',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
