# Generated by Django 2.1.8 on 2020-02-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRUD', '0006_auto_20190812_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('student_no', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_ins', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.Hostel_info')),
            ],
        ),
    ]
