# Generated by Django 2.1.8 on 2020-02-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passrate',
            old_name='user_ins',
            new_name='Hostel',
        ),
    ]
