# Generated by Django 2.1.8 on 2020-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passrate',
            name='pass_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
