# Generated by Django 2.1.8 on 2020-02-10 06:38

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20200210_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passrate',
            name='pass_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[Student.models.validate_unique_date]),
        ),
    ]
