# Generated by Django 2.1.8 on 2020-02-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_auto_20190812_0920'),
        ('Student', '0005_auto_20200210_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeno', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Hostel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.Hostel_info')),
            ],
        ),
    ]
