# Generated by Django 2.1.8 on 2020-02-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_likerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerate',
            old_name='likeno',
            new_name='likes',
        ),
    ]
